app:
    resource: '@AppBundle/Controller/'
    prefix: /api/v1
    type: annotation
    defaults:
        _format: json

api_login_check:
    path: /api/login_check

app_v2:
   resource: '@AppBundle/Controller/V2'
   prefix:   /api/v{version}
   requirements:
      version: '^2[\.0-9]*$'